WIDTH = 720
HEIGHT = 512

TILE_WIDTH = 48
TILE_HEIGHT = 32

PLAYER_WALKING_WIDTH = 72
PLAYER_WALKING_HEIGHT = 96
PLAYER_JUMPING_WIDTH = 84
PLAYER_JUMPING_HEIGHT = 108

PLAYER_X = WIDTH / 2
PLAYER_Y = HEIGHT * 0.8 - PLAYER_WALKING_HEIGHT

GRAVITY = 0.5
FRICTION = 0.4

PLAYER_VELOCITY_X = 5
PLAYER_VELOCITY_Y = -10

ENEMY_WIDTH = 96
ENEMY_HEIGHT = 72
